spring:
  datasource:
    url: jdbc:postgresql://pipa-db:5432/pipa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://pipa-db:5432/pipa
    user: postgres
    password: 1234

logging:
  level:
    org:
      flywaydb: debug

debug: true