INSERT INTO class_records (professional_crm, student_cpf, class_date, start_time, end_time, subject, status, location, discipline, media_id)
VALUES
    ('67890', '12345678901', '2024-06-22', '10:00:00', '12:00:00', 'Workshop de Fonoaudiologia', 'PLANNED', 'Sala 301', 'Fonoaudiologia', 1),
    ('78901', '23456789012', '2024-06-23', '14:00:00', '16:00:00', 'Aula Prática de Educação Física Adaptada', 'COMPLETED', 'Quadra Esportiva', 'Educação Física Adaptada', 2),
    ('89012', '34567890123', '2024-06-24', '09:30:00', '11:30:00', 'Discussão sobre Neuropsicologia Infantil', 'PLANNED', 'Sala 102', 'Neuropsicologia Infantil', 3),
    ('90123', '45678901234', '2024-06-25', '13:00:00', '15:00:00', 'Sessão de Acompanhamento Terapêutico', 'COMPLETED', 'Espaço Terapêutico', 'Acompanhante Terapêutico', 4),
    ('01234', '56789012345', '2024-06-26', '11:00:00', '13:00:00', 'Prática de Musicoterapia', 'PLANNED', 'Sala de Música', 'Musicoterapia', 5),
    ('12345', '67890123456', '2024-06-27', '15:00:00', '17:00:00', 'Palestra sobre Educação Especial', 'COMPLETED', 'Auditório Principal', 'Educação Especial', 6),
    ('23456', '78901234567', '2024-06-28', '10:30:00', '12:30:00', 'Inclusão Escolar', 'PLANNED', 'Sala 202', 'Educação Inclusiva', 7),
    ('34567', '89012345678', '2024-06-29', '14:00:00', '16:00:00', 'Pedagogia Inclusiva', 'COMPLETED', 'Sala de Reuniões', 'Pedagogia Inclusiva', 8),
    ('45678', '90123456789', '2024-06-30', '08:00:00', '10:00:00', 'Avaliação Psicopedagógica', 'PLANNED', 'Sala 303', 'Psicopedagogia', 9),
    ('56789', '01234567890', '2024-07-01', '13:30:00', '15:30:00', 'Terapia Ocupacional', 'COMPLETED', 'Sala 404', 'Terapeuta Ocupacional', 10),
    ('67890', '12345678901', '2024-07-02', '10:00:00', '12:00:00', 'Workshop de Fonoaudiologia', 'PLANNED', 'Sala 301', 'Fonoaudiologia', 11),
    ('78901', '23456789012', '2024-07-03', '14:00:00', '16:00:00', 'Aula Prática de Educação Física Adaptada', 'COMPLETED', 'Quadra Esportiva', 'Educação Física Adaptada', 12),
    ('89012', '34567890123', '2024-07-04', '09:30:00', '11:30:00', 'Discussão sobre Neuropsicologia Infantil', 'PLANNED', 'Sala 102', 'Neuropsicologia Infantil', 13),
    ('90123', '45678901234', '2024-07-05', '13:00:00', '15:00:00', 'Sessão de Acompanhamento Terapêutico', 'COMPLETED', 'Espaço Terapêutico', 'Acompanhante Terapêutico', 14),
    ('01234', '56789012345', '2024-07-06', '11:00:00', '13:00:00', 'Prática de Musicoterapia', 'PLANNED', 'Sala de Música', 'Musicoterapia', 15);
