INSERT INTO notes (notes, class_records_id)
VALUES
    ('Discussão sobre avaliação inicial.', 1),
    ('Apresentação de material didático adaptado.', 2),
    ('Acompanhamento individualizado dos alunos.', 3),
    ('Revisão de estratégias de ensino inclusivo.', 4),
    ('Discussão sobre métodos de avaliação.', 5),
    ('Apresentação de estudos de caso.', 6),
    ('Planejamento de atividades práticas.', 7),
    ('Feedback sobre o progresso dos alunos.', 8),
    ('Discussão sobre adaptação curricular.', 9),
    ('Apresentação de recursos tecnológicos.', 10),
    ('Análise de relatórios de evolução.', 11),
    ('Planejamento de saídas educativas.', 12),
    ('Discussão sobre recursos de acessibilidade.', 13),
    ('Revisão de estratégias de intervenção.', 14),
    ('Apresentação de jogos educativos.', 15);
