INSERT INTO users (cpf, username, password, type_user)
VALUES
    ('12345678901', 'joaodasilva1234', 'senha123', 'Family'),
    ('23456789012', 'mariaoliveira4567', 'senha456', 'Family'),
    ('34567890123', 'pedrosouza7890', 'senha789', 'Family'),
    ('45678901234', 'anasantos1234', 'senhaabc', 'Family'),
    ('56789012345', 'marcospereira5678', 'senha567', 'Family'),
    ('67890123456', 'carlaalmeida9012', 'senha901', 'Family'),
    ('78901234567', 'felipelima3456', 'senha345', 'Family'),
    ('89012345678', 'renatacosta6789', 'senha678', 'Family'),
    ('90123456789', 'joserodrigues2345', 'senha234', 'Family'),
    ('01234567890', 'laurafernandes5678', 'senha567', 'Family');


INSERT INTO users (crm, username, password, type_user)
VALUES
    ('12345', 'joanasilva1234', 'prof123', 'Professional'),
    ('23456', 'marcosoliveira5678', 'prof456', 'Professional'),
    ('34567', 'carolinasouza9012', 'prof789', 'Professional'),
    ('45678', 'gabrielsantos3456', 'profabc', 'Professional'),
    ('56789', 'isabelpereira6789', 'prof567', 'Professional'),
    ('67890', 'eduardoalmeida2345', 'prof901', 'Professional'),
    ('78901', 'renatalima5678', 'prof345', 'Professional'),
    ('89012', 'ricardocosta9012', 'prof678', 'Professional'),
    ('90123', 'camilarodrigues1234', 'prof234', 'Professional'),
    ('01234', 'leonardofernandes5678', 'prof567', 'Professional');
