INSERT INTO field_of_works (professional_crm, field_of_work)
VALUES
    ('12345', 'Educação Especial'),
    ('23456', 'Educação Inclusiva'),
    ('34567', 'Pedagogia Inclusiva'),
    ('45678', 'Psicopedagogia'),
    ('56789', 'Terapeuta Ocupacional'),
    ('67890', 'Fonoaudiologia'),
    ('78901', 'Educação Física Adaptada'),
    ('89012', 'Neuropsicologia Infantil'),
    ('90123', 'Acompanhante Terapêutico'),
    ('01234', 'Musicoterapia');